version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: teste_px
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: sh -c "chown -R www-data:www-data /var/www/html && chmod -R 777 /var/www/html/storage/* /var/www/html/bootstrap/cache/* && chmod -R 755 storage && chown -R www-data:www-data storage && chmod +x /var/www/html/entrypoint.sh && /var/www/html/entrypoint.sh && apache2-foreground && php artisan queue:work redis"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 4096M
        reservations:
          cpus: '2'
          memory: 1024M
  db:
    image: postgres:14
    container_name: postgres_px
    environment:
      POSTGRES_DB: px_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    container_name: redis_px
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=511
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
networks:
  app-network:
    driver: bridge
