FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    libzip-dev \
    curl \
    zip \
    && docker-php-ext-install pdo pdo_pgsql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY ./php/custom-php.ini /usr/local/etc/php/conf.d/
COPY ./src /var/www/html
ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN pecl install redis && docker-php-ext-enable redis

RUN a2enmod rewrite

RUN sed -i 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf

WORKDIR /var/www/html

EXPOSE 80
